package Algorithms;

import java.util.Arrays;

/**
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.
 */
public class FindTheDifference {

    public static char findTheDifference(String s, String t) {

        char[] s_char = s.toCharArray();
        char[] t_char = t.toCharArray();
        Arrays.sort(s_char);
        Arrays.sort(t_char);

        for(int i=0;i<s.length();i++){
            if(s_char[i] != t_char[i]){
                return t_char[i];
            }
        }
        return t_char[t.length()-1];

    }

    public static void main(String args[]){
        String s = "kreena";
        String t = "kreenam";
        System.out.println(findTheDifference(s,t));

    }
}
